### ISSUE TITLE
About ntrip client usage

### ISSUE THREAD

**Issue by wqrray** [goromal/ublox-F9P#1]
I can now get the correction data from ntrip client by launch a node and I can find a new "rtcm" node in the topic list, but how to use the correction data to do the correction for the position? The ublox_gps node seems unable to receive the correction data. I'm new to ROS, can you give me some hint on that?

**Comment by goromal** [comment]
Full disclosure that this is a forked repo that I am using for research; I’m not the original author of the RTCM correction functionality and haven’t used that part of the node personally. It looks like I initiated the repo because I committed it from scratch for some platform-specific reasons. That being said, running the command rqt_graph in a terminal while your setup is running will show if the rtcm topic is indeed being communicated from your server node to the gps node; just because it shows up in rostopic list doesn’t mean that it’s being actively communicated across the network. There are also a couple of rtcm-specific parameters to be set from what I see, so make sure that those parameters are being set correctly. If you want to talk to the original author, please see https://github.com/ros-agriculture/ublox_f9p.

**Comment by wqrray** [comment]
Thanks, do I need to change the parameters in the file zed-f9p.yaml?

**Comment by goromal** [comment]
Yes, depending on whichever parameter file is being loaded from your launch file. See ublox_gps/src/node.cpp for an idea of the parameters that need to be set.
